let car="honda";
let bike="suzuki";
let cycle="sohrab";
let color="green";
let age=15;
let grade=12;
let people=2;
let glass=5;
let animal="cat";
let ball=4;
console.log(car=="honda");
console.log(bike=="honda");
console.log(color=="green");
console.log(cycle=="honda");
console.log(age==15);
console.log(grade==1);
console.log(glass==5);
console.log(people==2);
console.log(ball==8);
console.log(animal=="horse");
